export type DocCallout = { tone: "note" | "warning" | "danger" | "success"; title: string; body: string };
export type DocSection = { heading: string; body?: string[]; code?: { label: string; value: string }; callout?: DocCallout; bullets?: string[]; table?: { headers: string[]; rows: string[][] } };
export type DocPage = { slug: string; group: string; title: string; summary: string; status?: string; sections: DocSection[] };

export const docs: DocPage[] = [
  {
    slug: "introduction", group: "Start here", title: "Introduction", summary: "Forge is a self-hosted control plane for applications, game servers, databases, backups, and node operations.",
    sections: [
      { heading: "What is in the control plane", body: ["Forge Web is the browser interface. Forge API persists desired state, runs API-facing services, and coordinates operations. PostgreSQL is the durable source of truth. Redis supports runtime coordination. The supplied Compose stack also includes monitoring, backups, and a reverse proxy."] },
      { heading: "What runs on a node", body: ["Beacon is the per-node execution agent. It receives authenticated work from Forge, uses the local Docker socket, stores workload files in its data directory, serves SFTP, reports health and observations, and retains no independent placement authority."] },
      { heading: "Choose a deployment", table: { headers: ["Model", "Use it when", "Reality"], rows: [["One VPS", "Learning, small installations, first TCP game server", "Web, API, PostgreSQL, Redis, Caddy, and one Beacon share one host."], ["Control plane + nodes", "Production workloads or recovery", "Keep Forge state on one host and deploy a Beacon Compose stack to every workload host."], ["Multiple nodes", "Evacuation or restore testing", "At least two healthy Beacons plus a shared backup destination are required."]] } },
      { heading: "Project status", callout: { tone: "warning", title: "Operate from verified capabilities", body: "The dashboard exposes a broad platform surface. Treat load balancing, evacuation, recovery, and cloud provisioning as operational features that need a tested topology and shared storage; do not assume automatic failover from their presence in the interface." } },
    ],
  },
  {
    slug: "architecture", group: "Start here", title: "Architecture overview", summary: "How browser traffic, durable state, background execution, and node actions fit together.",
    sections: [
      { heading: "Complete system", body: ["A browser reaches Forge Web through the public proxy. Web calls Forge API. The API stores state and migrations in PostgreSQL, uses Redis where configured, and coordinates commands with Beacon. Beacon controls the Docker runtime and its local workload files. Backup artifacts can be local or S3-compatible; multi-node restore needs a repository reachable from every eligible node."] },
      { heading: "Request and command flows", table: { headers: ["Flow", "Path"], rows: [["Browser request", "Browser → Caddy or Traefik → Forge Web; /api traffic is proxied to Forge API."], ["Game start", "Dashboard/API → stored operation → Beacon request → Docker/container/files → observation returned to Forge."], ["Application deployment", "Dashboard/API → deployment and revision records → Beacon build or Compose action → health observation → deployment status."], ["Backup and restore", "Beacon reads workload data → backup adapter → local or S3-compatible repository → destination Beacon restores and reports result."]] } },
      { heading: "Text topology", code: { label: "Architecture at a glance", value: "Browser\n  │ HTTPS 443\n  ▼\nCaddy or Traefik ─── Forge Web :3000\n  │ /api\n  ▼\nForge API :8080 ─── PostgreSQL :5432 (private)\n  │                 Redis :6379 (private)\n  │ authenticated commands / observations\n  ▼\nBeacon :9090 ─── Docker socket ─── workload containers\n  └── SFTP :2022 ─── node data directory" } },
      { heading: "Background execution", body: ["The current repository starts background services from the API process and from Beacon. There is no separately shipped Forge worker binary or systemd worker unit. API cron jobs are loaded from PostgreSQL when the cron service starts; Beacon also starts its own scheduler for node-side tasks."] },
    ],
  },
  {
    slug: "requirements", group: "Start here", title: "Requirements and supported platforms", summary: "Use the operating systems and deployment model the installer and Compose files actually support.",
    sections: [
      { heading: "Platform support", table: { headers: ["Platform", "Status", "Evidence"], rows: [["Ubuntu 22.04 LTS", "Supported", "Listed by scripts/install.sh."], ["Ubuntu 24.04 LTS", "Supported", "Listed by scripts/install.sh."], ["Debian 12", "Supported", "Listed by scripts/install.sh."], ["macOS 14–15", "Development only", "Recognized by the installer; do not use as a production Beacon host."], ["Other Linux", "Not tested", "No installer claim is made."], ["Windows", "Not supported for host deployment", "No supported installer path is supplied."]] } },
      { heading: "Host prerequisites", bullets: ["Docker Engine and the Docker Compose v2 plugin.", "A non-root operator account able to run Docker commands.", "A domain and public DNS control for public TLS.", "Outbound HTTPS access for image pulls, certificate issuance, Git, and optional object storage.", "A persistent disk for PostgreSQL and Beacon workload files."] },
      { heading: "Check Docker before installation", code: { label: "Host verification", value: "docker info\ndocker compose version\ndocker compose version --short" } },
      { heading: "Security boundary", callout: { tone: "danger", title: "Do not publish internal services", body: "PostgreSQL, Redis, the Beacon API, monitoring dashboards, and Caddy’s admin API are not public panel endpoints. In the production override they bind to loopback; expose only the proxy and deliberately allocated game ports." } },
    ],
  },
  {
    slug: "ubuntu-production", group: "Installation", title: "Ubuntu production installation", summary: "Start a one-host Forge Control Plane with the repository’s supplied Compose configuration.",
    sections: [
      { heading: "Before you run it", body: ["Use Ubuntu 22.04 or 24.04, a new directory owned by the deploy user, and a real secret file. The installer supports Ubuntu and Debian, but these commands keep each configuration decision visible."], callout: { tone: "warning", title: "Protect infra/.env", body: "It contains database credentials, API secrets, master keys, and a Beacon token. Do not commit it or copy a development file to production." } },
      { heading: "Install and configure", code: { label: "From the repository root", value: "git clone https://github.com/ryzenate1/forge-control-plane.git\ncd forge-control-plane\ncp infra/.env.example infra/.env\nchmod 600 infra/.env\n# edit infra/.env and set every required secret and public URL\n./scripts/install.sh" } },
      { heading: "Compose-first alternative", code: { label: "Validate then start", value: "cd infra\ndocker compose -f compose.yml -f compose.production.yml --env-file .env config --quiet\ndocker compose -f compose.yml -f compose.production.yml --env-file .env up -d --build\ndocker compose -f compose.yml -f compose.production.yml --env-file .env ps" } },
      { heading: "Verify", code: { label: "Repository health script", value: "./scripts/healthcheck.sh\n# or inspect only the control-plane stack\ncd infra && docker compose -f compose.yml -f compose.production.yml --env-file .env logs --tail 150 api web postgres redis" } },
    ],
  },
  {
    slug: "docker", group: "Installation", title: "Docker and service management", summary: "Forge is deployed with Docker Compose; Docker is the boot-time service manager used by the shipped production configuration.",
    sections: [
      { heading: "Supported service model", body: ["The repository does not ship a Forge API systemd unit, a Forge Web systemd unit, a Beacon systemd unit, or a systemd timer. Compose services use restart policies, and scripts/install.sh enables and starts the Docker system service when systemctl is available."] },
      { heading: "Everyday commands", code: { label: "From infra/", value: "docker compose -f compose.yml -f compose.production.yml --env-file .env ps\ndocker compose -f compose.yml -f compose.production.yml --env-file .env logs -f api\ndocker compose -f compose.yml -f compose.production.yml --env-file .env restart api\ndocker compose -f compose.yml -f compose.production.yml --env-file .env config --quiet\ndocker compose -f compose.yml -f compose.production.yml --env-file .env pull\ndocker compose -f compose.yml -f compose.production.yml --env-file .env up -d --build" } },
      { heading: "Persistent state", table: { headers: ["Service", "Persistent location", "Do not delete casually"], rows: [["PostgreSQL", "Named volume postgres-data", "Contains Forge state and migrations."], ["Redis", "Named volume redis-data", "Contains append-only Redis data."], ["Caddy", "Named caddy-data and caddy-config volumes", "Contains certificate and proxy state."], ["Beacon", "GAME_SERVERS_HOST_DIR mounted to DAEMON_DATA_DIR", "Contains game and workload files."]] } },
      { heading: "Destructive commands", callout: { tone: "danger", title: "Avoid volume deletion", body: "docker compose down does not remove named volumes by itself. Adding -v removes named volumes and can destroy Forge state. Confirm backups before using it." } },
    ],
  },
  {
    slug: "domain-tls", group: "Installation", title: "Domain, proxy, and TLS", summary: "Publish Forge Web and Forge API through a single HTTPS boundary.",
    sections: [
      { heading: "DNS first", body: ["Register a domain with any registrar. Create an A record for the panel hostname to the control-plane IPv4 address. Create an AAAA record only when the same host has working IPv6 and its firewall allows it. Check propagation before certificate requests."], code: { label: "DNS check", value: "dig +short panel.example.com A\ndig +short panel.example.com AAAA" } },
      { heading: "Supplied proxy options", table: { headers: ["Option", "Repository configuration", "Use"], rows: [["Caddy", "infra/compose.caddy.production.yml + infra/Caddyfile.production.example", "A public Caddy override routes the panel hostname to Web and /api to API. Copy the example first."], ["Traefik", "infra/compose.tls.yml", "The supplied TLS override obtains HTTP-01 certificates and routes the panel hostname to Web and /api to API."]] } },
      { heading: "Enable the supplied TLS override", code: { label: "From infra/", value: "# Set PANEL_DOMAIN, PANEL_URL, TRAEFIK_ACME_EMAIL and optional API_DOMAIN in .env\ndocker compose -f compose.yml -f compose.production.yml -f compose.tls.yml --env-file .env config --quiet\ndocker compose -f compose.yml -f compose.production.yml -f compose.tls.yml --env-file .env up -d" } },
      { heading: "Use Caddy instead", code: { label: "From infra/", value: "# Do not combine this with compose.tls.yml\ncp Caddyfile.production.example Caddyfile.production\n# Set PANEL_DOMAIN and PANEL_URL in .env\ndocker compose -f compose.yml -f compose.production.yml -f compose.caddy.production.yml --env-file .env config --quiet\ndocker compose -f compose.yml -f compose.production.yml -f compose.caddy.production.yml --env-file .env up -d\ndocker compose -f compose.yml -f compose.production.yml -f compose.caddy.production.yml --env-file .env logs -f caddy" } },
      { heading: "Firewall and certificate failures", callout: { tone: "warning", title: "HTTP-01 needs a reachable port 80", body: "Allow TCP 80 and 443 to the proxy. A failed certificate is commonly caused by incorrect DNS, an occupied port, an unreachable IPv6 address, or a CDN/proxy mode that prevents the challenge." } },
    ],
  },
  {
    slug: "beacon", group: "Beacon Node Guide", title: "What Beacon does", summary: "Beacon is Forge’s node agent. It runs Docker actions, files, console, SFTP, backups, and node reporting; it is not another web panel.",
    sections: [
      { heading: "Deployment models", table: { headers: ["Model", "Beacon location", "Use"], rows: [["All in one", "The daemon service in infra/compose.yml", "A first host where control plane and workloads share a VPS."], ["Standalone node", "infra/compose.beacon.yml on the workload VPS", "The supported node-specific Compose path."], ["Several nodes", "One standalone Beacon deployment per workload VPS", "Required for workload movement and destination recovery."]] } },
      { heading: "Network and identity", body: ["Beacon needs DAEMON_NODE_ID, DAEMON_NODE_TOKEN, and a PANEL_API_URL reachable from that node. The control plane uses the node credential for daemon calls; Beacon’s panel synchronization uses the panel API URL. The daemon health endpoint is /health. It binds its API at DAEMON_ADDR (default :9090) and SFTP is advertised at DAEMON_SFTP_ADDR (default :2022)."], callout: { tone: "warning", title: "Treat the Docker socket as root-equivalent", body: "Beacon mounts /var/run/docker.sock. Limit who can administer its host and do not expose its API publicly." } },
      { heading: "When Forge is unavailable", body: ["Already-running containers continue under Docker. New control-plane actions, state updates, and centralized observations cannot complete until the API and PostgreSQL return. A node cannot perform control-plane scheduling on its own." ] },
      { heading: "Health and logs", code: { label: "Standalone node", value: "cd infra\ndocker compose -f compose.beacon.yml --env-file .env ps\ndocker compose -f compose.beacon.yml --env-file .env logs -f beacon\ndocker compose -f compose.beacon.yml --env-file .env exec beacon /daemon --healthcheck" } },
    ],
  },
  {
    slug: "beacon-install", group: "Beacon Node Guide", title: "Install and enroll Beacon", summary: "Install the supported standalone Beacon Compose deployment on a separate Ubuntu workload node.",
    sections: [
      { heading: "Prerequisites", bullets: ["A supported Ubuntu or Debian host with Docker Engine and Compose v2.", "A node record and its ID/token from the Forge administration flow.", "A PANEL_API_URL that the node can reach over HTTP(S).", "A persistent directory for GAME_SERVERS_HOST_DIR."] },
      { heading: "Create the node configuration", code: { label: "On the Beacon host", value: "git clone https://github.com/ryzenate1/forge-control-plane.git\ncd forge-control-plane/infra\ncp ../beacon/.env.example .env\nchmod 600 .env\n# Set DAEMON_NODE_ID, DAEMON_NODE_TOKEN, PANEL_API_URL, and GAME_SERVERS_HOST_DIR\nmkdir -p /srv/game-panel/servers\n./bootstrap-beacon.sh" } },
      { heading: "Required ports", table: { headers: ["Port", "Purpose", "Exposure"], rows: [["9090/TCP", "Beacon API", "Keep private; production override binds it to loopback on an all-in-one host."], ["2022/TCP", "SFTP", "Standalone Compose uses host networking; bind is controlled by DAEMON_SFTP_BIND_ADDR. Restrict it or proxy it deliberately."], ["Allocated game ports", "Game traffic", "Open TCP and/or UDP only for allocations actually assigned."]] } },
      { heading: "Replace or remove a node", body: ["Drain the failed node before moving stateful workloads. Ensure a shared backup is present, enroll the replacement with new credentials, restore or redeploy workloads, verify health, then revoke the old node credential. Do not reuse a leaked node token."], code: { label: "Recreate the standalone container", value: "cd infra\ndocker compose -f compose.beacon.yml --env-file .env pull\ndocker compose -f compose.beacon.yml --env-file .env up -d --build\ndocker compose -f compose.beacon.yml --env-file .env logs --tail 150 beacon" } },
    ],
  },
  {
    slug: "databases", group: "Administration", title: "Databases", summary: "Forge’s internal PostgreSQL and Redis are not the same thing as databases provisioned for hosted workloads.",
    sections: [
      { heading: "Forge internal data services", table: { headers: ["Service", "Image and port", "Purpose"], rows: [["PostgreSQL", "postgres:16-alpine, private :5432", "Durable source of truth, migrations, control-plane records."], ["Redis", "redis:7-alpine, private :6379", "Runtime coordination with append-only persistence."], ["PostgreSQL backup", "postgres:16-alpine sidecar", "Scheduled database dumps to the configured local path and optional S3 settings."]] } },
      { heading: "Emergency inspection", code: { label: "From infra/", value: "docker compose -f compose.yml -f compose.production.yml --env-file .env exec postgres psql -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\"\ndocker compose -f compose.yml -f compose.production.yml --env-file .env exec redis redis-cli ping" } },
      { heading: "Hosted workload databases", body: ["The administration surface includes database services and managed database provisioning. The API wires a container provisioner to Beacon and Docker. Supported engine options must be selected in the dashboard and verified against the chosen node; keep their credentials, network exposure, backup policy, and lifecycle separate from Forge’s own PostgreSQL."], callout: { tone: "warning", title: "Do not grant workloads access to Forge PostgreSQL", body: "An application or game server should receive only its own database host, database, and least-privilege user." } },
      { heading: "Backup and restore", body: ["The control-plane backup sidecar uses POSTGRES_BACKUP_HOST_DIR by default and can receive S3_BACKUP_* configuration. Workload backup adapters are configured on Beacon with BACKUP_ADAPTER and S3_* variables. Test a restore on an eligible destination before relying on recovery." ] },
    ],
  },
  {
    slug: "operations", group: "Administration", title: "Applications, games, and operations", summary: "Use the panel’s workload areas to create, deploy, observe, and recover the workloads supported by Forge.",
    sections: [
      { heading: "Applications", body: ["The admin routes include applications, Dockerfile and image deployments, Compose stacks, Git providers, Git sources, deployment history, revisions, previews, domains, certificates, DNS providers, and application templates. Use the Applications area for workload configuration, the Deployments area for execution history and revisions, and Domains for exposure."], callout: { tone: "note", title: "Maturity guide", body: "A visible route is not a promise of a fully automated production workflow. Validate domain routing, Git webhooks, rollout strategy, and rollback in a non-critical environment before offering them as a service." } },
      { heading: "Game servers", body: ["The admin routes cover servers, nests, eggs, startup variables, allocations, mounts, files, terminal access, backups, and cron jobs. A game server requires an eligible Beacon node and a network allocation. Test UDP allocation paths and firewall rules before publishing UDP-dependent games." ] },
      { heading: "Infrastructure", body: ["Nodes, regions, locations, scheduler, autoscaler, traffic, load balancer, failover, health, monitoring, logs, Docker, host files, and host terminal are administrative capabilities. Host terminal and Docker administration cross a high-privilege boundary; restrict them to trusted operators." ] },
      { heading: "Operations and recovery", body: ["Use operations and activity history to inspect long-running work. Migration, evacuation, recovery, and failover screens require capacity, a healthy destination node, and shared backup access for stateful recovery. They are not a substitute for a tested disaster-recovery runbook." ] },
    ],
  },
  {
    slug: "schedules", group: "Administration", title: "Schedules, cron, mounts, and SFTP", summary: "Forge has application-side and node-side scheduling; it does not require an operator crontab entry for its normal scheduler.",
    sections: [
      { heading: "Cron truth", body: ["Forge API’s cron job service creates a robfig/cron scheduler with seconds enabled. On service start it loads enabled cron jobs from the store. A job is executed with sh -c inside the API process, and executions are recorded. Failed jobs retry when RetryCount is configured, with increasing 5-second delays. The service exposes a manual trigger path in its implementation."], callout: { tone: "warning", title: "Operational limit", body: "The inspected service has no distributed lock or explicit missed-run catch-up policy. Avoid long-running overlapping shell jobs and test schedules after API restarts." } },
      { heading: "No host crontab required", body: ["Do not add a crontab entry just to make Forge schedules run. Docker restart policies bring the API back; the API starts its scheduler. Beacon also starts its own scheduler for node-side tasks. The repository ships no systemd timer." ] },
      { heading: "Mounts and files", body: ["Mounts join a host directory to a workload container. Use explicit, restricted host paths; select read-only whenever writes are unnecessary. A mount must exist consistently on every destination node before migration. Browser file operations and SFTP access act on node-owned workload data, while host-file and terminal features are privileged administration tools." ] },
      { heading: "SFTP", body: ["Beacon starts SFTP from DAEMON_SFTP_ADDR and can use DAEMON_SFTP_BIND_ADDR for the low-level bind. Standalone Beacon uses host networking, so a broad bind can expose SFTP on the host. Keep it loopback-only or apply narrow firewall/proxy policy." ] },
    ],
  },
  {
    slug: "backup-recovery", group: "Operations", title: "Backups, migration, evacuation, and recovery", summary: "A backup is only useful after a verified restore on a node that can actually host the workload.",
    sections: [
      { heading: "Backup design", body: ["Local backups help one node. Cross-node recovery requires every eligible Beacon to reach the same S3-compatible repository and have the credentials and encryption context needed to restore. The Beacon Compose configuration accepts BACKUP_ADAPTER plus S3_BUCKET, S3_REGION, S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY, S3_ENDPOINT, S3_PREFIX, and S3_USE_PATH_STYLE." ] },
      { heading: "Evacuation runbook", code: { label: "Safe sequence", value: "1. Mark the source node unavailable for new placement.\n2. Verify a second Beacon is healthy and has capacity.\n3. Create and verify a backup in shared storage.\n4. Reserve the destination allocation and storage path.\n5. Restore or redeploy at the destination.\n6. Verify health, data, and public allocations.\n7. Retire the source only after verification." } },
      { heading: "Control-plane backup", code: { label: "Use the supplied scripts", value: "./scripts/upgrade.sh\n# review the backup directory configured by POSTGRES_BACKUP_HOST_DIR\n./scripts/rollback.sh list\n# restore only after taking a fresh backup and reading the command\n./scripts/rollback.sh db /var/backups/gamepanel/postgres/gamepanel-<timestamp>.dump" } },
      { heading: "Recovery limits", callout: { tone: "warning", title: "Restore-oriented recovery", body: "The current configuration provides backup and restore paths. It is not evidence of automatic ownership failover for a running stateful workload. Practice the runbook with a non-critical workload." } },
    ],
  },
  {
    slug: "reference", group: "Reference", title: "Ports, files, scripts, and maturity", summary: "A compact, code-aligned reference for the common operator values.",
    sections: [
      { heading: "Ports", table: { headers: ["Port", "Service", "Production exposure"], rows: [["80, 443/TCP", "Public proxy", "Public when serving the panel and TLS."], ["8080/TCP", "Forge API", "Loopback in compose.production.yml."], ["3000/TCP", "Forge Web", "Loopback in compose.production.yml."], ["5432/TCP", "PostgreSQL", "Loopback in compose.production.yml; never public."], ["6379/TCP", "Redis", "Loopback in compose.production.yml; never public."], ["9090/TCP", "Beacon API", "Loopback all-in-one; private in multi-node deployments."], ["2022/TCP", "Beacon SFTP", "Restrict deliberately; default bind is loopback in supplied Beacon Compose."], ["30000–30100/TCP+UDP", "Load-balancer allocation range", "Published by compose.production.yml when enabled."]] } },
      { heading: "Important files", table: { headers: ["Path", "Purpose"], rows: [["infra/.env", "Runtime secrets and deployment configuration."], ["infra/compose.yml", "Base control-plane Compose stack."], ["infra/compose.production.yml", "Production loopback bindings and restart policies."], ["infra/compose.beacon.yml", "Standalone Beacon Compose deployment."], ["infra/compose.tls.yml", "Traefik ACME and internal TLS override."], ["infra/Caddyfile", "Baseline Caddy configuration for local hostnames."], ["scripts/healthcheck.sh", "Compose, API, Beacon, Web, database, and monitoring checks."], ["scripts/rollback.sh", "Database/image rollback helper."]] } },
      { heading: "Feature maturity", table: { headers: ["Area", "Current position"], rows: [["One-host Compose stack", "Available"], ["Standalone Beacon Compose", "Available"], ["Node Docker and file execution", "Available"], ["Shared backup restore workflow", "Available when storage is configured and tested"], ["Automatic stateful failover", "Not currently available"], ["Load-balancer target selection", "Partially implemented; proxy deployment must be validated"], ["Cloud provisioning bootstrap", "Experimental; verify node enrollment and hardening"], ["Caddy public production configuration", "Requires operator adaptation; supplied Caddyfile is local-hostname oriented"]] } },
    ],
  },
  {
    slug: "troubleshooting", group: "Reference", title: "Troubleshooting", summary: "Start with service state, then use the repository’s health checks and focused logs.",
    sections: [
      { heading: "First response", code: { label: "Control-plane diagnosis", value: "./scripts/healthcheck.sh\n./scripts/diagnose.sh\ncd infra && docker compose -f compose.yml -f compose.production.yml --env-file .env ps\ncd infra && docker compose -f compose.yml -f compose.production.yml --env-file .env logs --tail 200 api daemon postgres redis web" } },
      { heading: "Common failures", table: { headers: ["Symptom", "Likely cause", "Check and fix"], rows: [["Beacon offline", "Wrong ID/token, unreachable PANEL_API_URL, or Docker failure", "Check standalone Beacon logs, then verify the three required variables and curl the panel API from the node."], ["SFTP refused", "No listener or restrictive bind/firewall", "Inspect DAEMON_SFTP_ADDR and DAEMON_SFTP_BIND_ADDR; use ss -lnt and the Beacon logs."], ["API unhealthy", "PostgreSQL, migration, Redis, or secret configuration", "Run scripts/healthcheck.sh and inspect API/PostgreSQL logs."], ["PostgreSQL auth failure", "DATABASE_URL and POSTGRES credentials differ", "Compare infra/.env values and reconnect with the Compose exec command."], ["TLS issuance fails", "DNS/port 80/IPv6/proxy conflict", "Use dig, confirm 80/443 ownership, then inspect Traefik logs."], ["Container will not start", "Image, allocation, disk, or Docker failure", "Inspect Beacon logs and Docker state on the assigned node."], ["Cron never runs", "Disabled or invalid schedule; API unavailable", "Confirm the saved schedule, enable it, then inspect API logs after restart."], ["Backup restore fails", "Destination cannot reach repository or lacks capacity", "Verify object-storage credentials from the node and the destination data path before retrying."]] } },
      { heading: "Escalate safely", callout: { tone: "danger", title: "Do not delete data to make an error disappear", body: "Capture logs, check the last successful backup, and preserve the PostgreSQL and Beacon data volumes before destructive repair actions." } },
    ],
  },
];

export const docGroups = [...new Set(docs.map((page) => page.group))];
export const docBySlug = (slug: string) => docs.find((page) => page.slug === slug);
