param(
    [string]$OutputPath = ".env",
    [string]$PanelDomain = $env:PANEL_DOMAIN
)

function New-HexSecret {
    param([int]$Bytes = 32)

    $buffer = New-Object byte[] $Bytes
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($buffer)
    }
    finally {
        $generator.Dispose()
    }
    return -join ($buffer | ForEach-Object { $_.ToString("x2") })
}

function New-Base64Secret {
    param([int]$Bytes = 32)

    $buffer = New-Object byte[] $Bytes
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($buffer)
    }
    finally {
        $generator.Dispose()
    }
    return [Convert]::ToBase64String($buffer) -replace '=+$', ''
}

if ([string]::IsNullOrWhiteSpace($PanelDomain)) {
    $PanelDomain = "panel.example.com"
    Write-Warning "PANEL_DOMAIN not set; using placeholder '$PanelDomain'."
}

$apiSecret = New-Base64Secret 32
$appKey = New-Base64Secret 32
$nodeTokenId = New-HexSecret 8
$nodeTokenSecret = New-HexSecret 32
$nodeToken = "$nodeTokenId.$nodeTokenSecret"
$nodeId = [Guid]::NewGuid().ToString()
$postgresPassword = New-Base64Secret 32
$grafanaPassword = New-HexSecret 24
$masterKey = New-Base64Secret 32
$redisPassword = New-Base64Secret 32
$soketiAppKey = New-HexSecret 16
$soketiAppSecret = New-HexSecret 32
$forgePreviousMasterKeys = ""
$cryptoKey = New-Base64Secret 32
$metricsToken = New-Base64Secret 32
$sftpHostKeyPassphrase = New-Base64Secret 32

@"
# Auto-generated by gen-env.ps1. Review before use. NEVER commit this file.
# Demo seeding is disabled and production startup is fail-closed on secrets.
APP_ENV=production
API_ADDR=:8080
API_AUTH_SECRET=$apiSecret
APP_KEY=$appKey
DATABASE_URL=postgres://gamepanel:$postgresPassword@postgres:5432/gamepanel?sslmode=prefer
POSTGRES_DB=gamepanel
POSTGRES_USER=gamepanel
POSTGRES_PASSWORD=$postgresPassword
POSTGRES_BACKUP_HOST_DIR=/var/backups/gamepanel/postgres
POSTGRES_BACKUP_INTERVAL_SECONDS=86400
POSTGRES_BACKUP_RETENTION_DAYS=14
REDIS_ADDR=redis:6379
REDIS_PASSWORD=$redisPassword
SOKETI_APP_ID=gamepanel
SOKETI_APP_KEY=$soketiAppKey
SOKETI_APP_SECRET=$soketiAppSecret
SOKETI_METRICS_PORT=9601
PANEL_URL=https://$PanelDomain
PANEL_API_URL=https://$PanelDomain/api/v1
DAEMON_ADDR=:9090
DAEMON_DATA_DIR=/srv/game-panel/servers
GAME_SERVERS_HOST_DIR=/srv/game-panel/servers
DAEMON_NODE_ID=$nodeId
DAEMON_NODE_TOKEN=$nodeToken
DAEMON_SFTP_HOST_KEY_PASSPHRASE=$sftpHostKeyPassphrase
DAEMON_UPGRADE_PUBLIC_KEY=
DAEMON_SFTP_ADDR=127.0.0.1:2022
DAEMON_SFTP_BIND_ADDR=0.0.0.0:2022
DAEMON_ALLOW_MOCK_RUNTIME=false
DAEMON_ALLOW_INSECURE_NO_AUTH=false
DAEMON_BACKUP_DIR=/srv/game-panel/servers/.beacon/backups
BEACON_DATABASE_PATH=/srv/game-panel/servers/.beacon/beacon.db
METRICS_TOKEN=$metricsToken
METRICS_TOKEN_FILE=./.metrics-token
LOAD_BALANCER_ENABLED=true
LOAD_BALANCER_BIND_HOST=
LOAD_BALANCER_PORT_MIN=30000
LOAD_BALANCER_PORT_MAX=30100
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$grafanaPassword
BACKUP_ADAPTER=local
FORGE_MASTER_KEY=$masterKey
FORGE_MASTER_KEY_ID=primary
FORGE_PREVIOUS_MASTER_KEYS=$forgePreviousMasterKeys
FORGE_ALLOW_EPHEMERAL_MASTER_KEY=false
MAIL_MAILER=log
MAIL_HOST=127.0.0.1
MAIL_PORT=587
MAIL_ENCRYPTION=tls
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_FROM_ADDRESS=noreply@$PanelDomain
MAIL_FROM_NAME=GamePanel
DB_MAX_OPEN_CONNS=25
DB_MAX_IDLE_CONNS=5
DB_CONN_MAX_LIFETIME=3600
LOG_LEVEL=info
LOG_FORMAT=text
LOG_OUTPUT=stdout
API_INTERNAL_URL=http://api:8080
BEACON_BASE_URL=http://127.0.0.1:9090
ALERTMANAGER_SMTP_HOST=
ALERTMANAGER_SMTP_PORT=587
ALERTMANAGER_SMTP_USER=
ALERTMANAGER_SMTP_PASS=
ALERTMANAGER_SMTP_FROM=noreply@$PanelDomain
ALERTMANAGER_ADMIN_EMAIL=
ALERTMANAGER_WEBHOOK_URL=
TRAEFIK_ACME_EMAIL=
TRAEFIK_CERTIFICATE_RESOLVER=letsencrypt
PANEL_DOMAIN=$PanelDomain
API_DOMAIN=api.$PanelDomain
PLUGINS_DIR=
LANGS_DIR=lang
MIGRATIONS_DIR=/migrations
#CRYPTO_KEY=$cryptoKey
"@ | Set-Content -LiteralPath $OutputPath -Encoding ASCII
$outputDirectory = Split-Path -Parent $OutputPath
if ([string]::IsNullOrWhiteSpace($outputDirectory)) { $outputDirectory = "." }
$metricsToken | Set-Content -LiteralPath (Join-Path $outputDirectory ".metrics-token") -Encoding ASCII -NoNewline

Write-Host "Wrote production environment template to $OutputPath"
