#!/usr/bin/env bash
# ======================================================================
# gen-env.sh — GamePanel Production .env Generator
#
# Generates a complete production .env file with cryptographically
# random secrets.  Can run interactively or silently.
#
# Usage:
#   ./gen-env.sh [output-path]              interactive
#   ./gen-env.sh --silent [output-path]     silent (all random)
#
# Preset any variable via environment (e.g. PANEL_DOMAIN=x.example.com).
# Idempotent: safe to run multiple times (overwrites existing file).
#
# Requirements: openssl, bash 4+
# ======================================================================
set -euo pipefail

# ---- Paths & Mode ----------------------------------------------------------
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${1:-"$SELF_DIR/.env"}"
SILENT=false

if [ "${1:-}" = "--silent" ]; then
    SILENT=true
    OUTPUT="${2:-"$SELF_DIR/.env"}"
fi

# ---- Helpers ---------------------------------------------------------------
rand_base64() { openssl rand -base64 32 | tr -d '\n'; }
rand_hex()    { openssl rand -hex "${1:-32}"; }
rand_hex24()  { rand_hex 24; }
rand_hex16()  { rand_hex 16; }
rand_hex8()   { rand_hex 8; }
make_token()  { echo "$(rand_hex8).$(rand_hex32)"; }
make_uuid()   { local h; h="$(rand_hex 16)"; echo "${h:0:8}-${h:8:4}-${h:12:4}-${h:16:4}-${h:20:12}"; }
rand_hex32()  { rand_hex 32; }

# ---- Interactive Prompts ---------------------------------------------------
if [ "$SILENT" = false ]; then
    cat <<WELCOME
=== GamePanel .env Generator ===
Output: $OUTPUT
Press Enter to accept defaults (shown in brackets).
Leave secrets blank for random generation.

WELCOME

    read -r -p "Panel domain [panel.example.com]: " PANEL_DOMAIN
    PANEL_DOMAIN="${PANEL_DOMAIN:-panel.example.com}"

    read -r -p "PostgreSQL database name [gamepanel]: " PG_DB
    PG_DB="${PG_DB:-gamepanel}"
    read -r -p "PostgreSQL username [gamepanel]: " PG_USER
    PG_USER="${PG_USER:-gamepanel}"
    read -r -s -p "PostgreSQL password [random]: " PG_PASSWORD
    echo ""

    read -r -p "Grafana admin user [admin]: " GF_USER
    GF_USER="${GF_USER:-admin}"
    read -r -s -p "Grafana admin password [random]: " GF_PASSWORD
    echo ""

    read -r -p "Mail driver (smtp/sendmail/log) [log]: " MAIL_DRIVER
    MAIL_DRIVER="${MAIL_DRIVER:-log}"

    read -r -p "Backup adapter (local/s3) [local]: " BK_ADAPTER
    BK_ADAPTER="${BK_ADAPTER:-local}"

    read -r -p "AWS region (blank to skip): " AWS_REGION

    read -r -p "Traefik ACME email (for Let's Encrypt, blank to skip): " TRAEFIK_ACME_EMAIL

    read -r -p "Alertmanager admin email (blank to skip): " ALERTMANAGER_ADMIN_EMAIL

    read -r -p "Alertmanager webhook URL (Slack/Discord, blank to skip): " ALERTMANAGER_WEBHOOK_URL

    echo ""
    echo "Generating secrets..."
else
    PANEL_DOMAIN="${PANEL_DOMAIN:-panel.example.com}"
    PG_DB="${PG_DB:-gamepanel}"
    PG_USER="${PG_USER:-gamepanel}"
    GF_USER="${GF_USER:-admin}"
    MAIL_DRIVER="${MAIL_DRIVER:-log}"
    BK_ADAPTER="${BK_ADAPTER:-local}"
    AWS_REGION="${AWS_REGION:-}"
    TRAEFIK_ACME_EMAIL="${TRAEFIK_ACME_EMAIL:-}"
    ALERTMANAGER_ADMIN_EMAIL="${ALERTMANAGER_ADMIN_EMAIL:-}"
    ALERTMANAGER_WEBHOOK_URL="${ALERTMANAGER_WEBHOOK_URL:-}"
fi

# ---- Generate Random Secrets -----------------------------------------------
: "${PG_PASSWORD:=$(rand_base64)}"
: "${GF_PASSWORD:=$(rand_hex24)}"

POSTGRES_PASSWORD="$PG_PASSWORD"
POSTGRES_DB="$PG_DB"
POSTGRES_USER="$PG_USER"
DATABASE_URL="postgres://${PG_USER}:${POSTGRES_PASSWORD}@postgres:5432/${PG_DB}?sslmode=disable"

API_AUTH_SECRET="$(rand_base64)"
APP_KEY="$(rand_base64)"
FORGE_MASTER_KEY="$(rand_base64)"
CRYPTO_KEY="$(rand_base64)"
NODE_ID="$(make_uuid)"
NODE_TOKEN="$(make_token)"
GRAFANA_ADMIN_USER="$GF_USER"
GRAFANA_ADMIN_PASSWORD="$GF_PASSWORD"
SOKETI_APP_KEY="$(rand_hex16)"
SOKETI_APP_SECRET="$(rand_hex32)"

# ---- Write Output File -----------------------------------------------------
mkdir -p "$(dirname "$OUTPUT")"
cat > "$OUTPUT" <<ENV
# =====================================================================
# GamePanel Production Environment
# Auto-generated by gen-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# WARNING: This file contains secrets — NEVER commit it to version
# control.  Keep it secure and restricted (chmod 600).
# =====================================================================
# Quick Start:
#   1. Review PANEL_URL, DAEMON_NODE_ID, DAEMON_NODE_TOKEN,
#      PANEL_API_URL, BEACON_PANEL_API_URL, DAEMON_SFTP_BIND_ADDR.
#   2. Run:
#      docker compose -f compose.yml -f compose.production.yml \\
#          --env-file .env up -d
#   3. Complete the /setup wizard, then restart daemon + monitoring
#      with the assigned DAEMON_NODE_ID.
# =====================================================================

# =====================================================================
# --- Database (PostgreSQL) ---
# =====================================================================
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=${DATABASE_URL}
POSTGRES_BACKUP_HOST_DIR=/var/backups/gamepanel/postgres
POSTGRES_BACKUP_INTERVAL_SECONDS=86400
POSTGRES_BACKUP_RETENTION_DAYS=14

# =====================================================================
# --- Redis ---
# =====================================================================
REDIS_ADDR=redis:6379
REDIS_PASSWORD=

# =====================================================================
# --- Soketi / WebSocket (optional — requires compose.realtime.yml) ---
# =====================================================================
SOKETI_APP_ID=gamepanel
SOKETI_APP_KEY=${SOKETI_APP_KEY}
SOKETI_APP_SECRET=${SOKETI_APP_SECRET}
SOKETI_METRICS_PORT=9601

# =====================================================================
# --- Panel URL ---
# =====================================================================
PANEL_URL=https://${PANEL_DOMAIN}

# =====================================================================
# --- API Configuration ---
# =====================================================================
API_ADDR=:8080
API_AUTH_SECRET=${API_AUTH_SECRET}
APP_KEY=${APP_KEY}
APP_ENV=production
LOAD_BALANCER_ENABLED=true
LOAD_BALANCER_BIND_HOST=
LOAD_BALANCER_PORT_MIN=30000
LOAD_BALANCER_PORT_MAX=30100

# =====================================================================
# --- Encryption at Rest ---
# FORGE_MASTER_KEY must be exactly 32 bytes, base64 or base64url
# encoded.  If lost, ALL encrypted data becomes permanently
# unrecoverable.
# =====================================================================
FORGE_MASTER_KEY=${FORGE_MASTER_KEY}
FORGE_MASTER_KEY_ID=primary
FORGE_PREVIOUS_MASTER_KEYS=
FORGE_ALLOW_EPHEMERAL_MASTER_KEY=false

# =====================================================================
# --- Daemon / Node Token ---
# Format: <token_id>.<secret>
# Generate a new token from the panel web UI after deployment.
# =====================================================================
DAEMON_NODE_TOKEN=${NODE_TOKEN}

# =====================================================================
# --- Daemon (Beacon) Configuration ---
# =====================================================================
DAEMON_ADDR=:9090
DAEMON_SFTP_ADDR=:2022
DAEMON_SFTP_BIND_ADDR=127.0.0.1:2022
DAEMON_DATA_DIR=/srv/game-panel/servers
GAME_SERVERS_HOST_DIR=/srv/game-panel/servers
DAEMON_NODE_ID=${NODE_ID}
DAEMON_ALLOW_MOCK_RUNTIME=false
PANEL_API_URL=http://api:8080/api/v1
BEACON_PANEL_API_URL=https://${PANEL_DOMAIN}/api/v1

# =====================================================================
# --- AWS Node Bootstrap (optional) ---
# Uncomment and fill in to enable auto-scaling of beacon nodes.
# =====================================================================
#AWS_REGION=
#AWS_ACCESS_KEY_ID=
#AWS_SECRET_ACCESS_KEY=
#AWS_SUBNET_ID=
#AWS_SECURITY_GROUP_IDS=sg-0123456789abcdef0
#AWS_IAM_INSTANCE_PROFILE=gamepanel-beacon
#AWS_BEACON_IMAGE=ghcr.io/example/gamepanel-beacon:stable

# =====================================================================
# --- Grafana ---
# =====================================================================
GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER}
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

# =====================================================================
# --- Backup Adapter ---
# =====================================================================
BACKUP_ADAPTER=${BK_ADAPTER}
#S3_BUCKET=my-game-panel-backups
#S3_REGION=us-east-1
#S3_ACCESS_KEY_ID=
#S3_SECRET_ACCESS_KEY=
#S3_ENDPOINT=https://s3.amazonaws.com
#S3_PREFIX=panel/
#S3_USE_PATH_STYLE=true
#S3_BACKUP_BUCKET=my-game-panel-backups
#S3_BACKUP_REGION=us-east-1
#S3_BACKUP_ACCESS_KEY_ID=
#S3_BACKUP_SECRET_ACCESS_KEY=
#S3_BACKUP_PREFIX=postgres

# =====================================================================
# --- Email / SMTP ---
# =====================================================================
MAIL_MAILER=${MAIL_DRIVER}
MAIL_HOST=127.0.0.1
MAIL_PORT=587
MAIL_ENCRYPTION=tls
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_FROM_ADDRESS=noreply@${PANEL_DOMAIN}
MAIL_FROM_NAME=GamePanel

# =====================================================================
# --- Database Connection Pool ---
# =====================================================================
DB_MAX_OPEN_CONNS=25
DB_MAX_IDLE_CONNS=5
DB_CONN_MAX_LIFETIME=3600

# =====================================================================
# --- Logging ---
# =====================================================================
LOG_LEVEL=info
LOG_FORMAT=text
LOG_OUTPUT=stdout

# =====================================================================
# --- Internal Service URLs ---
# =====================================================================
API_INTERNAL_URL=http://api:8080
BEACON_BASE_URL=http://127.0.0.1:9090

# =====================================================================
# --- Alertmanager (monitoring alerts) ---
# =====================================================================
ALERTMANAGER_SMTP_HOST=
ALERTMANAGER_SMTP_PORT=587
ALERTMANAGER_SMTP_USER=
ALERTMANAGER_SMTP_PASS=
ALERTMANAGER_SMTP_FROM=noreply@${PANEL_DOMAIN}
ALERTMANAGER_ADMIN_EMAIL=${ALERTMANAGER_ADMIN_EMAIL}
ALERTMANAGER_WEBHOOK_URL=${ALERTMANAGER_WEBHOOK_URL}

# =====================================================================
# --- TLS / ACME Configuration (required for compose.tls.yml) ---
# =====================================================================
TRAEFIK_ACME_EMAIL=${TRAEFIK_ACME_EMAIL}
TRAEFIK_CERTIFICATE_RESOLVER=letsencrypt
PANEL_DOMAIN=${PANEL_DOMAIN}
API_DOMAIN=api.${PANEL_DOMAIN}

# =====================================================================
# --- Directory Paths (mounts) ---
# =====================================================================
PLUGINS_DIR=
LANGS_DIR=lang
MIGRATIONS_DIR=/migrations
BATCH2_MIGRATIONS_DIR=/batch2-migrations

# =====================================================================
# --- Extra Keys ---
# CRYPTO_KEY is a general-purpose encryption key.  Uncomment below if
# your deployment requires it (not used by the default compose stack).
# =====================================================================
#CRYPTO_KEY=${CRYPTO_KEY}
ENV

chmod 600 "$OUTPUT"

# ---- Validate Required Variables -------------------------------------------
missing=0
required_vars="POSTGRES_PASSWORD DATABASE_URL API_AUTH_SECRET APP_KEY FORGE_MASTER_KEY DAEMON_NODE_TOKEN GRAFANA_ADMIN_PASSWORD PANEL_URL DAEMON_NODE_ID"

for var in $required_vars; do
    line=$(grep -E "^(#)?${var}=" "$OUTPUT" 2>/dev/null || true)
    if [ -z "$line" ]; then
        echo "ERROR: $var is missing from $OUTPUT" >&2
        missing=$((missing + 1))
        continue
    fi
    val=$(echo "$line" | cut -d= -f2-)
    if [ -z "$val" ]; then
        echo "ERROR: $var is empty in $OUTPUT" >&2
        missing=$((missing + 1))
    fi
done

if [ "$missing" -gt 0 ]; then
    echo "FATAL: $missing required variable(s) missing or empty." >&2
    exit 1
fi

echo "OK: $(echo "$required_vars" | wc -w | tr -d ' ') required variables present and non-empty."
echo "Generated: $OUTPUT"
