ALTER TABLE replica_applications
  ADD COLUMN IF NOT EXISTS image TEXT NOT NULL DEFAULT 'nginx:alpine',
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS generation INTEGER NOT NULL DEFAULT 0;
