-- Phase 3: unified one-click service catalog.
-- Lists every managed service kind the panel can provision (databases,
-- caches and queues) with their supported versions. Seed rows are inserted
-- idempotently so the file is safe to run on any existing install.
CREATE TABLE IF NOT EXISTS catalog_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    key VARCHAR(100) UNIQUE NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category VARCHAR(50) NOT NULL DEFAULT 'database',
    versions JSONB NOT NULL DEFAULT '[]'::jsonb,
    default_version VARCHAR(50) NOT NULL DEFAULT '',
    icon VARCHAR(500) NOT NULL DEFAULT '',
    requires JSONB NOT NULL DEFAULT '[]'::jsonb,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_catalog_entries_enabled ON catalog_entries(enabled);

INSERT INTO catalog_entries
    (key, display_name, description, category, versions, default_version, icon, requires, sort_order)
VALUES
    ('postgres', 'PostgreSQL',
     'Reliable open-source relational database with advanced type system and JSON support.',
     'database', '["16","15","14"]', '16',
     'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/postgresql.svg',
     '["username","password","database","port"]', 1),
    ('mysql', 'MySQL',
     'The world''s most popular open-source relational database.',
     'database', '["8.3","8.0"]', '8.3',
     'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/mysql.svg',
     '["username","password","database","port"]', 2),
    ('mariadb', 'MariaDB',
     'MySQL-compatible relational database maintained by the MariaDB foundation.',
     'database', '["11","10"]', '11',
     'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/mariadb.svg',
     '["username","password","database","port"]', 3),
    ('redis', 'Redis',
     'In-memory data structure store used as cache, session store and queue.',
     'cache', '["7","6"]', '7',
     'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/redis.svg',
     '["password","port"]', 4),
    ('mongodb', 'MongoDB',
     'Document-oriented NoSQL database with a flexible JSON data model.',
     'database', '["7","6"]', '7',
     'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/mongodb.svg',
     '["username","password","database","port"]', 5),
    ('valkey', 'Valkey',
     'Redis-compatible open-source in-memory data store and cache.',
     'cache', '["8","7"]', '8',
     'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/redis.svg',
     '["password","port"]', 6),
    ('redis-queue', 'Redis Queue',
     'Redis tuned for short-lived job/queue workloads with bounded memory.',
     'queue', '["7","6"]', '7',
     'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/redis.svg',
     '["password","port"]', 7),
    ('rabbitmq', 'RabbitMQ',
     'Feature-rich message broker implementing AMQP 0-9-1.',
     'queue', '["4","3"]', '4',
     'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/rabbitmq.svg',
     '["username","password","port"]', 8),
    ('clickhouse', 'ClickHouse',
     'Columnar online-analytical-processing database for analytics at scale.',
     'database', '["latest"]', 'latest',
     'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/clickhouse.svg',
     '["username","password","database","port"]', 9),
    ('nats', 'NATS',
     'Lightweight high-throughput publish/subscribe message server.',
     'message', '["2"]', '2',
     'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/nats.svg',
     '["port"]', 10),
    ('memcached', 'Memcached',
     'Distributed in-memory key-value store for caching hot data',
     'cache', '["2"]', '2',
     'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/memcached.svg',
     '["port"]', 11)
ON CONFLICT (key) DO NOTHING;