package compose

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"gamepanel/forge/internal/store"

	"github.com/compose-spec/compose-go/v2/types"
)

// ComposeImportService handles importing Docker Compose files into Forge applications
type ComposeImportService struct {
	store          *store.Store
	parser         *ComposeParser
	logger         *slog.Logger
	composeService *Service
}

// NewComposeImportService creates a new Compose import service
func NewComposeImportService(store *store.Store, parser *ComposeParser, composeService *Service, logger *slog.Logger) *ComposeImportService {
	if parser == nil {
		parser = NewDefaultComposeParser("")
	}
	if logger == nil {
		logger = slog.Default()
	}
	return &ComposeImportService{
		store:          store,
		parser:         parser,
		logger:         logger,
		composeService: composeService,
	}
}

// ImportRequest represents a request to import a Compose file
type ImportRequest struct {
	Name        string            `json:"name"`
	Content     string            `json:"content"`
	NodeID      string            `json:"nodeId,omitempty"`
	Environment map[string]string `json:"environment,omitempty"`
	MemoryMB    int64             `json:"memoryMb,omitempty"`
	CPUShares   int64             `json:"cpuShares,omitempty"`
	DiskMB      int64             `json:"diskMb,omitempty"`
}

// ImportResult represents the result of importing a Compose file
type ImportResult struct {
	Project          *store.ComposeStack `json:"project,omitempty"`
	ParsedConfig     *ParsedCompose      `json:"parsedConfig,omitempty"`
	ValidationResult *ValidateResult     `json:"validationResult,omitempty"`
	ServiceMappings  map[string]string   `json:"serviceMappings,omitempty"`
	Error            string              `json:"error,omitempty"`
}

// ServiceMapping represents the mapping between Compose services and Forge services
type ServiceMapping struct {
	ComposeServiceName string   `json:"composeServiceName"`
	ForgeServiceName   string   `json:"forgeServiceName"`
	ForgeServiceID     string   `json:"forgeServiceId,omitempty"`
	Image              string   `json:"image,omitempty"`
	Ports              []string `json:"ports,omitempty"`
	Environment        []string `json:"environment,omitempty"`
	Volumes            []string `json:"volumes,omitempty"`
	Networks           []string `json:"networks,omitempty"`
}

// ImportComposeProject imports a Docker Compose file and creates equivalent Forge application configuration
func (s *ComposeImportService) ImportComposeProject(ctx context.Context, req *ImportRequest) (*ImportResult, error) {
	if req == nil {
		return nil, fmt.Errorf("import request cannot be nil")
	}

	if strings.TrimSpace(req.Name) == "" {
		return nil, fmt.Errorf("project name is required")
	}

	if strings.TrimSpace(req.Content) == "" {
		return nil, fmt.Errorf("compose content is required")
	}

	s.logger.Info("Starting Compose import", "project_name", req.Name)

	// Step 1: Parse the Compose file using the library parser
	project, err := s.parser.ParseComposeString(req.Content, "import.yaml")
	if err != nil {
		s.logger.Error("Failed to parse Compose file", "error", err)
		return nil, fmt.Errorf("failed to parse compose file: %w", err)
	}

	// Step 2: Validate the Compose file
	validationResult := s.composeService.ValidateCompose([]byte(req.Content), "")
	if !validationResult.Valid {
		s.logger.Warn("Compose validation failed", "errors", validationResult.Errors, "warnings", validationResult.Warnings)
		return &ImportResult{
			ValidationResult: validationResult,
			Error:            "validation failed",
		}, fmt.Errorf("compose validation failed: %v", validationResult.Errors)
	}

	// Step 3: Normalize to Forge models
	parsedConfig, err := s.parser.NormalizeToForgeModels(project)
	if err != nil {
		s.logger.Error("Failed to normalize Compose to Forge models", "error", err)
		return nil, fmt.Errorf("failed to normalize compose: %w", err)
	}

	// Step 4: Create service mappings
	serviceMappings, err := s.createServiceMappings(project, parsedConfig)
	if err != nil {
		s.logger.Error("Failed to create service mappings", "error", err)
		return nil, fmt.Errorf("failed to create service mappings: %w", err)
	}

	// Step 5: Create the Forge project/stack
	composeYAML := req.Content
	composeHash := s.generateComposeHash(composeYAML)

	// Set defaults if not provided
	memoryMB := req.MemoryMB
	if memoryMB == 0 {
		memoryMB = 512 // Default 512MB
	}

	cpuShares := req.CPUShares
	if cpuShares == 0 {
		cpuShares = 512 // Default 512 CPU shares
	}

	diskMB := req.DiskMB
	if diskMB == 0 {
		diskMB = 1024 // Default 1GB
	}

	// Create the ComposeStack
	stack := &store.ComposeStack{
		ID:           "", // Will be generated by store
		UserID:       "", // Will be set by the caller
		Name:         req.Name,
		NodeID:       req.NodeID,
		Status:       "imported",
		ComposeYAML:  composeYAML,
		ComposeHash:  composeHash,
		EnvVars:      req.Environment,
		MemoryMB:     memoryMB,
		CPUShares:    cpuShares,
		DiskMB:       diskMB,
	}

	// Step 6: Save to database
	if s.store != nil {
		if err := s.store.CreateComposeStack(ctx, stack); err != nil {
			s.logger.Error("Failed to create compose stack", "error", err)
			return nil, fmt.Errorf("failed to create compose stack: %w", err)
		}
	}

	// Convert service mappings to a simple map for the result
	serviceMappingMap := make(map[string]string)
	for _, mapping := range serviceMappings {
		serviceMappingMap[mapping.ComposeServiceName] = mapping.ForgeServiceName
	}

	s.logger.Info("Compose import completed successfully", "project_id", stack.ID, "service_count", len(serviceMappings))

	return &ImportResult{
		Project:          stack,
		ParsedConfig:     parsedConfig,
		ValidationResult: validationResult,
		ServiceMappings:  serviceMappingMap,
	}, nil
}

// createServiceMappings creates mappings between Compose services and Forge services
func (s *ComposeImportService) createServiceMappings(project *types.Project, parsedConfig *ParsedCompose) ([]ServiceMapping, error) {
	if project == nil || parsedConfig == nil {
		return nil, fmt.Errorf("project and parsedConfig cannot be nil")
	}

	mappings := make([]ServiceMapping, 0, len(project.Services))

	for _, svc := range parsedConfig.Services {
		// Generate a unique Forge service name based on the Compose service name
		forgeServiceName := s.generateForgeServiceName(svc.Name)

		envSlice := make([]string, 0, len(svc.Environment))
		for k, v := range svc.Environment {
			envSlice = append(envSlice, k+"="+v)
		}
		mapping := ServiceMapping{
			ComposeServiceName: svc.Name,
			ForgeServiceName:   forgeServiceName,
			Image:              svc.Image,
			Ports:              svc.Ports,
			Environment:        envSlice,
			Volumes:            svc.Volumes,
			Networks:           s.getServiceNetworks(project, svc.Name),
		}

		mappings = append(mappings, mapping)
	}

	return mappings, nil
}

// generateForgeServiceName generates a Forge-compatible service name from a Compose service name
func (s *ComposeImportService) generateForgeServiceName(composeServiceName string) string {
	// Forge service names should be lowercase, alphanumeric with hyphens
	name := strings.ToLower(composeServiceName)

	// Replace underscores with hyphens
	name = strings.ReplaceAll(name, "_", "-")

	// Remove any characters that aren't alphanumeric or hyphens
	var result strings.Builder
	for _, c := range name {
		if (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' {
			result.WriteRune(c)
		}
	}

	name = result.String()

	// Ensure it doesn't start or end with a hyphen
	name = strings.Trim(name, "-")

	// If empty after processing, use a default
	if name == "" {
		name = "service"
	}

	return name
}

// getServiceNetworks returns the networks for a specific service
func (s *ComposeImportService) getServiceNetworks(project *types.Project, serviceName string) []string {
	if project == nil {
		return []string{}
	}

	svc, exists := project.Services[serviceName]
	if !exists {
		return []string{}
	}

	networks := make([]string, 0, len(svc.Networks))
	for netName := range svc.Networks {
		networks = append(networks, netName)
	}

	return networks
}

// generateComposeHash generates a hash for the Compose content
func (s *ComposeImportService) generateComposeHash(content string) string {
	if content == "" {
		return ""
	}
	h := sha256.Sum256([]byte(content))
	return hex.EncodeToString(h[:])
}

// ImportComposeFromFile imports a Compose file from a filesystem path
func (s *ComposeImportService) ImportComposeFromFile(ctx context.Context, filePath string, req *ImportRequest) (*ImportResult, error) {
	if req == nil {
		req = &ImportRequest{}
	}

	content, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read compose file: %w", err)
	}

	if req.Name == "" {
		// Use the filename (without extension) as the project name
		baseName := filepath.Base(filePath)
		nameWithoutExt := strings.TrimSuffix(baseName, filepath.Ext(baseName))
		req.Name = nameWithoutExt
	}

	req.Content = string(content)

	return s.ImportComposeProject(ctx, req)
}

// ImportComposeWithGit imports a Compose file from a Git repository
func (s *ComposeImportService) ImportComposeWithGit(ctx context.Context, repoURL, branch, composePath string, req *ImportRequest) (*ImportResult, error) {
	tmpDir, err := os.MkdirTemp("", "compose-git-*")
	if err != nil {
		return nil, fmt.Errorf("failed to create temp directory: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	args := []string{"clone", "--depth", "1"}
	if branch != "" {
		args = append(args, "--branch", branch)
	}
	args = append(args, repoURL, tmpDir)

	cmd := exec.CommandContext(ctx, "git", args...)
	if out, err := cmd.CombinedOutput(); err != nil {
		return nil, fmt.Errorf("git clone failed: %s: %w", strings.TrimSpace(string(out)), err)
	}

	filePath := filepath.Join(tmpDir, composePath)
	return s.ImportComposeFromFile(ctx, filePath, req)
}

// ValidateComposeForImport validates a Compose file specifically for import compatibility
func (s *ComposeImportService) ValidateComposeForImport(content []byte) (*ValidateResult, error) {
	// Use the existing compose service validation
	return s.composeService.ValidateCompose(content, ""), nil
}

// GetImportPreview provides a preview of what would be imported without actually creating resources
func (s *ComposeImportService) GetImportPreview(content string) (*ImportPreview, error) {
	if strings.TrimSpace(content) == "" {
		return nil, fmt.Errorf("content is required")
	}

	// Parse the Compose file
	project, err := s.parser.ParseComposeString(content, "preview.yaml")
	if err != nil {
		return nil, fmt.Errorf("failed to parse compose: %w", err)
	}

	// Normalize to Forge models
	parsedConfig, err := s.parser.NormalizeToForgeModels(project)
	if err != nil {
		return nil, fmt.Errorf("failed to normalize compose: %w", err)
	}

	// Create service mappings
	serviceMappings, err := s.createServiceMappings(project, parsedConfig)
	if err != nil {
		return nil, fmt.Errorf("failed to create service mappings: %w", err)
	}

	// Validate
	validationResult := s.composeService.ValidateCompose([]byte(content), "")

	return &ImportPreview{
		ProjectName:      parsedConfig.Name,
		ComposeVersion:   parsedConfig.Version,
		ServiceCount:     len(parsedConfig.Services),
		NetworkCount:     len(parsedConfig.Networks),
		VolumeCount:      len(parsedConfig.Volumes),
		SecretCount:      len(parsedConfig.Secrets),
		ConfigCount:      len(parsedConfig.Configs),
		ServiceMappings:  serviceMappings,
		ValidationResult: validationResult,
		ParsedConfig:     parsedConfig,
	}, nil
}

// ImportPreview provides a preview of what would be imported
type ImportPreview struct {
	ProjectName      string           `json:"projectName"`
	ComposeVersion   string           `json:"composeVersion"`
	ServiceCount     int              `json:"serviceCount"`
	NetworkCount     int              `json:"networkCount"`
	VolumeCount      int              `json:"volumeCount"`
	SecretCount      int              `json:"secretCount"`
	ConfigCount      int              `json:"configCount"`
	ServiceMappings  []ServiceMapping `json:"serviceMappings"`
	ValidationResult *ValidateResult  `json:"validationResult"`
	ParsedConfig     *ParsedCompose   `json:"parsedConfig"`
}

// ImportComposeStack creates a Compose stack from an import request
func (s *ComposeImportService) ImportComposeStack(ctx context.Context, userID string, req *ImportRequest) (*store.ComposeStack, error) {
	if s.store == nil {
		return nil, fmt.Errorf("store is required")
	}

	// First validate the import
	preview, err := s.GetImportPreview(req.Content)
	if err != nil {
		return nil, fmt.Errorf("failed to get import preview: %w", err)
	}

	if !preview.ValidationResult.Valid {
		return nil, fmt.Errorf("compose validation failed: %v", preview.ValidationResult.Errors)
	}

	// Set defaults
	if req.MemoryMB == 0 {
		req.MemoryMB = 512
	}
	if req.CPUShares == 0 {
		req.CPUShares = 512
	}
	if req.DiskMB == 0 {
		req.DiskMB = 1024
	}

	// Create the stack
	stack := &store.ComposeStack{
		UserID:       userID,
		Name:         req.Name,
		NodeID:       req.NodeID,
		Status:       "imported",
		ComposeYAML:  req.Content,
		ComposeHash:  s.generateComposeHash(req.Content),
		EnvVars:      req.Environment,
		MemoryMB:     req.MemoryMB,
		CPUShares:    req.CPUShares,
		DiskMB:       req.DiskMB,
	}

	// Create the stack in the database
	if err := s.store.CreateComposeStack(ctx, stack); err != nil {
		return nil, fmt.Errorf("failed to create compose stack: %w", err)
	}

	return stack, nil
}

// min returns the minimum of two integers
func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// max returns the maximum of two integers
func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
