ALTER TABLE builds ADD COLUMN IF NOT EXISTS node_id TEXT;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS registry TEXT;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS cache_from TEXT[] DEFAULT '{}';
ALTER TABLE builds ADD COLUMN IF NOT EXISTS cache_to TEXT[] DEFAULT '{}';
ALTER TABLE builds ADD COLUMN IF NOT EXISTS platform TEXT DEFAULT 'linux/amd64';
ALTER TABLE builds ADD COLUMN IF NOT EXISTS commit_sha TEXT;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS commit_ref TEXT;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS digest TEXT;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS retry_of TEXT;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS retry_attempt INTEGER DEFAULT 0;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS timed_out BOOLEAN DEFAULT FALSE;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS build_timeout_secs INTEGER DEFAULT 1800;
ALTER TABLE builds ADD COLUMN IF NOT EXISTS credentials_masked BOOLEAN DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS builds_node_idx ON builds (node_id);
CREATE INDEX IF NOT EXISTS builds_status_idx ON builds (status);
