import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: "var(--ink)",
        surface: "var(--surface)",
        paper: "var(--paper)",
        line: "var(--line)",
        muted: "var(--muted)",
        red: {
          DEFAULT: "var(--red)",
          50: "var(--red-wash)",
          100: "var(--red-wash)",
          200: "#fecaca",
          300: "#fca5a5",
          400: "#f87171",
          500: "var(--red)",
          600: "var(--red)",
          700: "var(--red-dark)",
          800: "var(--red-dark)",
          900: "var(--red-dark)",
        },
        "red-dark": "var(--red-dark)",
        "red-wash": "var(--red-wash)",
        "surface-hover": "var(--surface-hover)",
        green: {
          DEFAULT: "var(--green)",
          50: "var(--green-light)",
          100: "var(--green-light)",
          200: "var(--green-border)",
          300: "#86efac",
          400: "#4ade80",
          500: "var(--green)",
          600: "var(--green)",
          700: "var(--green-dark)",
          800: "var(--green-dark)",
          900: "var(--green-dark)",
        },
        "green-light": "var(--green-light)",
        "green-border": "var(--green-border)",
        "green-dark": "var(--green-dark)",
        amber: {
          DEFAULT: "var(--amber)",
          50: "#fffbeb",
          100: "#fef3c7",
          200: "#fde68a",
          300: "#fcd34d",
          400: "#fbbf24",
          500: "var(--amber)",
          600: "var(--amber)",
          700: "#b45309",
          800: "#92400e",
          900: "#78350f",
        },
        nav: "var(--nav)",
        "nav-line": "var(--nav-line)",
      },
      fontFamily: {
        sans: ["Manrope", "Arial", "sans-serif"],
        mono: ["DM Mono", "monospace"],
        serif: ["Newsreader", "Georgia", "serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;
